services:
    app:
        env_file:
            - bitwarden.env
        build:
            dockerfile: ./Dockerfile.dev
        volumes:
            - ./:/app
            - /app/node_modules
            - /app/.next
        ports:
            - "3000:3000"
        entrypoint: ./entrypoint.sh
