import LocalizedStrings from 'react-localization';

let localizationStrings = new LocalizedStrings({
    en: {
        //auth page text
        emailLabel: "Email address",
        emailPlaceholder: "Enter email",
        passwordLabel: "Password",
        passwordPlaceholder: "Password",
        login: "Login",
        signUp: "Sign up",
        forgotPassword: "Forgot your password?",
        //nav bar text
        home: "Home",
        facilityUpload: "Facility Upload",
        admin: "Admin",
        adminLogin: "Admin Login",
        signOut: "Sign Out",
        searchProviderName: "Search provider name",
        searchZipcode: "Search zipcode",
        hideLabel: "Hide",
        showLabel: "Show",
        languagesLabel: "Languages",
        agesLabel: "Ages",
        insuranceLabel: "Insurance",
        serviceTypeLabel: "Service Type",
        specializationsLabel: "Specializations",
        therapyTypeLabel: "Therapy Types",
        moreFilters: "More Filters",
        lessFilters: "Less Filters",
    },
    es: {
        //auth page text
        emailLabel: "Dirección de correo electrón",
        emailPlaceholder: "Ingrese correo electrónico",
        passwordLabel: "Contraseña",
        passwordPlaceholder: "Contraseña",
        login: "Iniciar sesión",
        signUp: "Inscribirse",
        forgotPassword: "Olvidaste tu contraseña",
        //nav bar text
        home: "Casa",
        facilityUpload: "Facilidad de carga",
        admin: "Administrador",
        adminLogin: "Inicio de sesión de administrador",
        signOut: "Cerrar  sesión",
        searchProviderName: "Nombre del proveedor de búsqueda",
        searchZipcode: "Buscar código postal",
        hideLabel: "Esconder",
        showLabel: "Mostrar",
        languagesLabel: "Idiomas",
        agesLabel: "Edad",
        insuranceLabel: "Seguro",
        serviceTypeLabel: "Tipo de servicio",
        specializationsLabel: "Especializaciones",
        therapyTypeLabel: "Tipos de terapia",
        moreFilters: "Mas filtros",
        lessFilters: "Menos filtros",
    },
    zh: {
        //auth page text
        emailLabel: "邮箱地址",
        emailPlaceholder: "输入邮箱地址",
        passwordLabel: "密码",
        passwordPlaceholder: "密码",
        login: "登陆",
        signUp: "注册",
        forgotPassword: "忘记你的密码？",
        //nav bar text
        home: "主页",
        facilityUpload: "设备上传",
        admin: "管理人员登陆",
        adminLogin: "管理人员登陆",
        signOut: "退出登录",
        searchProviderName: "搜素供应商名称",
        searchZipcode: "搜索邮编",
        hideLabel: "隐藏",
        showLabel: "展示",
        languagesLabel: "语言",
        agesLabel: "年龄",
        insuranceLabel: "保险",
        serviceTypeLabel: "服务类型",
        specializationsLabel: "专项研究",
        therapyTypeLabel: "疗法",
        moreFilters: "增加筛选条件",
        lessFilters: "减少筛选条件",
    }
});

export default localizationStrings;
